# agent_type: qfil
# agent_dir: trained_models
# agent_fname: jse0svn6
# obs_type: rgb
# kinematics_dim: 2


# agent:
#   type: dagger
#   dir: trained_models
#   fname: ky7i5vvo


### SMGC

# gpu_index: 0
# sim_index: 0

# agent:
#   type: smgc
#   dir: trained_models
#   fname: smgc

# environment:
#   env_type: dynamics
#   env_dim: 2
#   obs_type: vector

### DAgger Target IR

# gpu_index: 0
# sim_index: 3

# agent:
#   type: dagger
#   dir: trained_models
#   fname: nzzjiv0s

# environment:
#   env_type: dynamics
#   env_dim: 2
#   obs_type: target-ir

### DAgger Point IR

# gpu_index: 0
# sim_index: 0

# agent:
#   type: dagger
#   dir: trained_models
#   fname: 01ww03vf

# environment:
#   env_type: dynamics
#   env_dim: 2
#   obs_type: point-ir


# dagger target-ir nzzjiv0s
# dagger point-ir

# dagger target-ir ky7i5vvo
# dagger point-ir c3ixealo

gpu_index: 0
sim_index: 0

agent:
  type: qfil
  dir: trained_models
  fname: qf6bqgm0.pt

environment:
  env_type: kinematics
  env_dim: 2
  obs_type: vector
