dir: trained_models/estimator
fname: f6q5302z
obs_type: point-ir

gpu_idx: 0
sim_idx: 2

# agent_type: png
# agent_dir: png
# agent_fname: png
# obs_type: vector
# kinematics_dim: 3
# sim_idx: 0

# qfil vector 45weoh6w
# qfil rgb jse0svn6
# qfil ir wj9glnon
# dagger vector g4xs9vxt
# dagger rgb ccaxs37a
# dagger ir ki1mji1k
