gpu_index: 0
sim_index: 0

num_updates: 200000
num_rollouts: 5
num_steps: 2000

batch_size: 256
n_eval: 10
eval_freq: 10000
log_freq: 100

environment:
  env_type: dynamics
  env_dim: 2
  obs_type: point-ir
  ctrl_gain: 200
  beta_decay: 0.95

agent:
  num_actors: 4
  buffer_size: 200000
  lr: 0.0003

wandb:
  project: ai-missile
  name: dagger-point-2d-dynamics
  group:
  mode: online
