gpu_index: 0
sim_index: 0
num_epochs: 10
batch_size: 200
learning_rate: 0.001
buffer_size: 100000

environment:
  obs_type: point-ir
  kinematics_dim: 3
  png_gain: 5

wandb:
  project: ai-missile
  name: estimator-3d
  mode: online