num_updates: 200000
num_rollouts: 10
num_steps: 2000

batch_size: 256
n_eval: 10
eval_freq: 10000
log_freq: 100

buffer_size: 200000
learning_rate: 0.0001

gpu_index: 0
sim_index: 0

environment:
  obs_type: point-ir
  kinematics_dim: 3
  png_gain: 5
  beta_decay: 0.95

wandb:
  project: ai-missile
  name: estimator-point-3d
  group: 
  mode: online